Description: ElasticsearchDomain resource

Parameters:

  MicroserviceName:
    Description: A microservice name that will be prefixed to resource names
    Type: String
    
  ElasticsearchVersion:
    Description: Elasticsearch Version
    Type: String
    Default: '6.0'

  InstanceType: 
    Description: Which instance type should we use to build the ES Domain?
    Type: String
    Default: m4.large.elasticsearch

  Subnets:
    Description: two subnets in which microservice will operate
    Type: String

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    
Resources:

  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: indexer-es-domain
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: 10
        InstanceType: !Ref InstanceType
        ZoneAwarenessEnabled: true
        DedicatedMasterEnabled: true
        DedicatedMasterCount: 3
        DedicatedMasterType: m4.large.elasticsearch
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 500
        VolumeType: gp2
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/indexer-es-domain/*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions:
        SubnetIds: !Ref Subnets
        SecurityGroupIds:
          - !Ref SecurityGroup

Outputs:

  ESDomainArn:
    Description: ElasticSearch Domain arn
    Value: !GetAtt ElasticsearchDomain.DomainArn
    
  ESDomainEndpoint:
    Description: The URL endpoint for the ElasticSearch Domain
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
