Description: ElasticsearchDomain resource

Parameters:

  MicroserviceName:
    Description: A microservice name that will be prefixed to resource names
    Type: String
    
  ElasticsearchVersion:
    Description: Elasticsearch Version
    Type: String
    Default: '6.0'

  InstanceType: 
    Description: Which instance type should we use to build the ES Domain?
    Type: String
    Default: m4.large.elasticsearch

  Subnet1:
    Description: First subnet
    Type: String

  Subnet2:
    Description: Second subnet
    Type: String

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      DomainName: indexer-es-domain
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: '2'
        InstanceType: !Ref InstanceType
        ZoneAwarenessEnabled: true
      EBSOptions:
        EBSEnabled: 'true'
        Iops: 0
        VolumeSize: 10
        VolumeType: standard
      SnapshotOptions:
        AutomatedSnapshotStartHour: '0'
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      VPCOptions:
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !Ref SecurityGroup

Outputs:

  ESDomainArn:
    Description: ElasticSearch Domain arn
    Value: !GetAtt ElasticsearchDomain.DomainArn
    
  ESDomainEndpoint:
    Description: The URL endpoint for the ElasticSearch Domain
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
