Description: >
    Master Template for Deployng SM Microservice 
    
Parameters:
    
    DebugMode:
        Description: DebugMode toggle. If yes, public access to the microservice will be allowed
        Type: String
        AllowedValues: 
            - NO
            - YES
        
    PeerVPC:
        Description: If DebugMode==No, specify peer VPC to communicate with, otherwise, specify any VPC
        Type: AWS::EC2::VPC::Id
        Default: ""

    Deploy:
        Description: What to deploy GREEN, BLUE, or BOTH (ES update is under construction)
        Type: String
        AllowedValues: 
            - GREEN
            - BLUE
            - BOTH
            - ES

Conditions:

    DeployGreen: !Or
        - !Equals [ !Ref Deploy, "GREEN" ]
        - !Equals [ !Ref Deploy, "BOTH" ]
        
    DeployBlue: !Or
        - !Equals [ !Ref Deploy, "BLUE" ]
        - !Equals [ !Ref Deploy, "BOTH" ]
        
    DeployES: !Equals [ !Ref Deploy, "ES" ]

Resources:

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/infra/vpc.yml'
            Parameters:
                MicroserviceName:   !Ref AWS::StackName
                VpcCIDR:            10.50.32.0/19
                PublicSubnet1CIDR:  10.50.32.0/22
                PublicSubnet2CIDR:  10.50.36.0/22
                PrivateSubnet1CIDR: 10.50.40.0/22
                PrivateSubnet2CIDR: 10.50.44.0/22
                DebugMode:          !Ref DebugMode
                PeerVPC:            !Ref PeerVPC

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/infra/security-groups.yml'
            Parameters: 
                MicroserviceName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC

    ALB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/infra/load-balancers.yml'
            Parameters:
                MicroserviceName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Subnets: !GetAtt VPC.Outputs.PublicSubnets
                SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

    ElasticSearch:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:  !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/es/es-domain.yml'
            Parameters:
                MicroserviceName: !Ref AWS::StackName
                ElasticsearchVersion: '6.0'
                InstanceType: m4.large.elasticsearch
                Subnet1: !GetAtt VPC.Outputs.PrivateSubnet1
                Subnet2: !GetAtt VPC.Outputs.PrivateSubnet2
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ESServiceSecurityGroup

    ECS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/ecs/cluster.yml'
            Parameters:
                MicroserviceName: !Ref AWS::StackName
                InstanceType: m4.large
                ClusterSize: 1
                MaxClusterSize: 10
                VPC: !GetAtt VPC.Outputs.VPC
                SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
                Subnets: !GetAtt VPC.Outputs.PrivateSubnets

    ServiceGreen:
        Type: AWS::CloudFormation::Stack
        Condition: DeployGreen
        Properties:
            TemplateURL: !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/ecs/service-green.yml'
            Parameters:
                MicroserviceName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 1
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /prod

    ServiceBlue:
        Type: AWS::CloudFormation::Stack
        Condition: DeployBlue
        Properties:
            TemplateURL: !Sub 'https://s3-${AWS::Region}.amazonaws.com/sm-msi-s3/cfn/ecs/service-blue.yml'
            Parameters:
                MicroserviceName: !Ref AWS::StackName
                VPC: !GetAtt VPC.Outputs.VPC
                Cluster: !GetAtt ECS.Outputs.Cluster
                DesiredCount: 1
                Listener: !GetAtt ALB.Outputs.Listener 
                Path: /prod

Outputs:

    MicroserviceUrl: 
        Description: The URL endpoint for the microservice
        Value: !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "prod" ]]
